source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Sticker' do
  pod 'SwiftHTTP', '~> 0.9.2'
  pod 'JSONJoy-Swift', '~> 0.9.1'
  pod 'NibDesignable', '~> 1.0.4'
end
